### PR TITLE
Upgrade all of the things

### PR DESCRIPTION
**Pull request by mfeckie**
This PR upgrades to latest ember-cli and addresses deprecations around the use of `ext/promise`.

I'm not sure if this library is still maintained, but we still use it 😄 

I have a follow up PR for `ember-cli-build-front-end-build-pack` if this gets accepted

### CODE REVIEW

**Comment by mfeckie** [comment]
This doesn't seem to work as I'd hoped.  Closing for now

**Comment by samselikoff** [comment]
Ok - we don't use this anymore but are happy to merge anything you need.

**Comment by mfeckie** [comment]
@samselikoff  As a curiosity, what do you folks prefer to do / use now?

**Comment by samselikoff** [comment]
@mfeckie We moved to using two separate heroku apps, one for our frontend one for our backend. I think if we were still at a job like our last one we'd be using something like this.

@ryanto may have some more insight. You could also join #topic-embermap in the Ember Slack to chat :)

**Pull request closed without merging**
